workflows:
  flutter-build-workflow:
    name: Flutter Web, Android & iOS Simulator Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Analyze code
        script: |
          flutter analyze
      - name: Build Web
        script: |
          flutter build web --release
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build iOS Simulator (for Appetize.io)
        script: |
          flutter build ios --simulator
          cd build/ios/iphonesimulator
          zip -r app-simulator.zip Runner.app
    artifacts:
      - build/web/**
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphonesimulator/app-simulator.zip

  ios-testflight-workflow:
    name: iOS Release to TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: Admin_Key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: keychain initialize
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files "city.swim.school" --type IOS_APP_STORE --create
      - name: Add certs to keychain
        script: keychain add-certificates
      - name: Apply profiles to Xcode
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build iOS (IPA)
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
