import 'package:freezed_annotation/freezed_annotation.dart';

part 'admin_task.freezed.dart';
part 'admin_task.g.dart';

enum TaskPriority { urgent, today, flexible, completed }

@freezed
abstract class AdminTask with _$AdminTask {
  const factory AdminTask({
    required String id,
    required String title,
    required String subtitle,
    required TaskPriority priority,
    required DateTime createdAt,
    @Default(false) bool isAutoGenerated,
  }) = _AdminTask;

  factory AdminTask.fromJson(Map<String, dynamic> json) => _$AdminTaskFromJson(json);
}
