// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'admin_task.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_AdminTask _$AdminTaskFromJson(Map<String, dynamic> json) => _AdminTask(
  id: json['id'] as String,
  title: json['title'] as String,
  subtitle: json['subtitle'] as String,
  priority: $enumDecode(_$TaskPriorityEnumMap, json['priority']),
  createdAt: DateTime.parse(json['createdAt'] as String),
  isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
);

Map<String, dynamic> _$AdminTaskToJson(_AdminTask instance) =>
    <String, dynamic>{
      'id': instance.id,
      'title': instance.title,
      'subtitle': instance.subtitle,
      'priority': _$TaskPriorityEnumMap[instance.priority]!,
      'createdAt': instance.createdAt.toIso8601String(),
      'isAutoGenerated': instance.isAutoGenerated,
    };

const _$TaskPriorityEnumMap = {
  TaskPriority.urgent: 'urgent',
  TaskPriority.today: 'today',
  TaskPriority.flexible: 'flexible',
  TaskPriority.completed: 'completed',
};
