// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'admin_task.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// dart format off
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$AdminTask {

 String get id; String get title; String get subtitle; TaskPriority get priority; DateTime get createdAt; bool get isAutoGenerated;
/// Create a copy of AdminTask
/// with the given fields replaced by the non-null parameter values.
@JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
$AdminTaskCopyWith<AdminTask> get copyWith => _$AdminTaskCopyWithImpl<AdminTask>(this as AdminTask, _$identity);

  /// Serializes this AdminTask to a JSON map.
  Map<String, dynamic> toJson();


@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is AdminTask&&(identical(other.id, id) || other.id == id)&&(identical(other.title, title) || other.title == title)&&(identical(other.subtitle, subtitle) || other.subtitle == subtitle)&&(identical(other.priority, priority) || other.priority == priority)&&(identical(other.createdAt, createdAt) || other.createdAt == createdAt)&&(identical(other.isAutoGenerated, isAutoGenerated) || other.isAutoGenerated == isAutoGenerated));
}

@JsonKey(includeFromJson: false, includeToJson: false)
@override
int get hashCode => Object.hash(runtimeType,id,title,subtitle,priority,createdAt,isAutoGenerated);

@override
String toString() {
  return 'AdminTask(id: $id, title: $title, subtitle: $subtitle, priority: $priority, createdAt: $createdAt, isAutoGenerated: $isAutoGenerated)';
}


}

/// @nodoc
abstract mixin class $AdminTaskCopyWith<$Res>  {
  factory $AdminTaskCopyWith(AdminTask value, $Res Function(AdminTask) _then) = _$AdminTaskCopyWithImpl;
@useResult
$Res call({
 String id, String title, String subtitle, TaskPriority priority, DateTime createdAt, bool isAutoGenerated
});




}
/// @nodoc
class _$AdminTaskCopyWithImpl<$Res>
    implements $AdminTaskCopyWith<$Res> {
  _$AdminTaskCopyWithImpl(this._self, this._then);

  final AdminTask _self;
  final $Res Function(AdminTask) _then;

/// Create a copy of AdminTask
/// with the given fields replaced by the non-null parameter values.
@pragma('vm:prefer-inline') @override $Res call({Object? id = null,Object? title = null,Object? subtitle = null,Object? priority = null,Object? createdAt = null,Object? isAutoGenerated = null,}) {
  return _then(_self.copyWith(
id: null == id ? _self.id : id // ignore: cast_nullable_to_non_nullable
as String,title: null == title ? _self.title : title // ignore: cast_nullable_to_non_nullable
as String,subtitle: null == subtitle ? _self.subtitle : subtitle // ignore: cast_nullable_to_non_nullable
as String,priority: null == priority ? _self.priority : priority // ignore: cast_nullable_to_non_nullable
as TaskPriority,createdAt: null == createdAt ? _self.createdAt : createdAt // ignore: cast_nullable_to_non_nullable
as DateTime,isAutoGenerated: null == isAutoGenerated ? _self.isAutoGenerated : isAutoGenerated // ignore: cast_nullable_to_non_nullable
as bool,
  ));
}

}


/// Adds pattern-matching-related methods to [AdminTask].
extension AdminTaskPatterns on AdminTask {
/// A variant of `map` that fallback to returning `orElse`.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case _:
///     return orElse();
/// }
/// ```

@optionalTypeArgs TResult maybeMap<TResult extends Object?>(TResult Function( _AdminTask value)?  $default,{required TResult orElse(),}){
final _that = this;
switch (_that) {
case _AdminTask() when $default != null:
return $default(_that);case _:
  return orElse();

}
}
/// A `switch`-like method, using callbacks.
///
/// Callbacks receives the raw object, upcasted.
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case final Subclass2 value:
///     return ...;
/// }
/// ```

@optionalTypeArgs TResult map<TResult extends Object?>(TResult Function( _AdminTask value)  $default,){
final _that = this;
switch (_that) {
case _AdminTask():
return $default(_that);case _:
  throw StateError('Unexpected subclass');

}
}
/// A variant of `map` that fallback to returning `null`.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case _:
///     return null;
/// }
/// ```

@optionalTypeArgs TResult? mapOrNull<TResult extends Object?>(TResult? Function( _AdminTask value)?  $default,){
final _that = this;
switch (_that) {
case _AdminTask() when $default != null:
return $default(_that);case _:
  return null;

}
}
/// A variant of `when` that fallback to an `orElse` callback.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case _:
///     return orElse();
/// }
/// ```

@optionalTypeArgs TResult maybeWhen<TResult extends Object?>(TResult Function( String id,  String title,  String subtitle,  TaskPriority priority,  DateTime createdAt,  bool isAutoGenerated)?  $default,{required TResult orElse(),}) {final _that = this;
switch (_that) {
case _AdminTask() when $default != null:
return $default(_that.id,_that.title,_that.subtitle,_that.priority,_that.createdAt,_that.isAutoGenerated);case _:
  return orElse();

}
}
/// A `switch`-like method, using callbacks.
///
/// As opposed to `map`, this offers destructuring.
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case Subclass2(:final field2):
///     return ...;
/// }
/// ```

@optionalTypeArgs TResult when<TResult extends Object?>(TResult Function( String id,  String title,  String subtitle,  TaskPriority priority,  DateTime createdAt,  bool isAutoGenerated)  $default,) {final _that = this;
switch (_that) {
case _AdminTask():
return $default(_that.id,_that.title,_that.subtitle,_that.priority,_that.createdAt,_that.isAutoGenerated);case _:
  throw StateError('Unexpected subclass');

}
}
/// A variant of `when` that fallback to returning `null`
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case _:
///     return null;
/// }
/// ```

@optionalTypeArgs TResult? whenOrNull<TResult extends Object?>(TResult? Function( String id,  String title,  String subtitle,  TaskPriority priority,  DateTime createdAt,  bool isAutoGenerated)?  $default,) {final _that = this;
switch (_that) {
case _AdminTask() when $default != null:
return $default(_that.id,_that.title,_that.subtitle,_that.priority,_that.createdAt,_that.isAutoGenerated);case _:
  return null;

}
}

}

/// @nodoc
@JsonSerializable()

class _AdminTask implements AdminTask {
  const _AdminTask({required this.id, required this.title, required this.subtitle, required this.priority, required this.createdAt, this.isAutoGenerated = false});
  factory _AdminTask.fromJson(Map<String, dynamic> json) => _$AdminTaskFromJson(json);

@override final  String id;
@override final  String title;
@override final  String subtitle;
@override final  TaskPriority priority;
@override final  DateTime createdAt;
@override@JsonKey() final  bool isAutoGenerated;

/// Create a copy of AdminTask
/// with the given fields replaced by the non-null parameter values.
@override @JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
_$AdminTaskCopyWith<_AdminTask> get copyWith => __$AdminTaskCopyWithImpl<_AdminTask>(this, _$identity);

@override
Map<String, dynamic> toJson() {
  return _$AdminTaskToJson(this, );
}

@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is _AdminTask&&(identical(other.id, id) || other.id == id)&&(identical(other.title, title) || other.title == title)&&(identical(other.subtitle, subtitle) || other.subtitle == subtitle)&&(identical(other.priority, priority) || other.priority == priority)&&(identical(other.createdAt, createdAt) || other.createdAt == createdAt)&&(identical(other.isAutoGenerated, isAutoGenerated) || other.isAutoGenerated == isAutoGenerated));
}

@JsonKey(includeFromJson: false, includeToJson: false)
@override
int get hashCode => Object.hash(runtimeType,id,title,subtitle,priority,createdAt,isAutoGenerated);

@override
String toString() {
  return 'AdminTask(id: $id, title: $title, subtitle: $subtitle, priority: $priority, createdAt: $createdAt, isAutoGenerated: $isAutoGenerated)';
}


}

/// @nodoc
abstract mixin class _$AdminTaskCopyWith<$Res> implements $AdminTaskCopyWith<$Res> {
  factory _$AdminTaskCopyWith(_AdminTask value, $Res Function(_AdminTask) _then) = __$AdminTaskCopyWithImpl;
@override @useResult
$Res call({
 String id, String title, String subtitle, TaskPriority priority, DateTime createdAt, bool isAutoGenerated
});




}
/// @nodoc
class __$AdminTaskCopyWithImpl<$Res>
    implements _$AdminTaskCopyWith<$Res> {
  __$AdminTaskCopyWithImpl(this._self, this._then);

  final _AdminTask _self;
  final $Res Function(_AdminTask) _then;

/// Create a copy of AdminTask
/// with the given fields replaced by the non-null parameter values.
@override @pragma('vm:prefer-inline') $Res call({Object? id = null,Object? title = null,Object? subtitle = null,Object? priority = null,Object? createdAt = null,Object? isAutoGenerated = null,}) {
  return _then(_AdminTask(
id: null == id ? _self.id : id // ignore: cast_nullable_to_non_nullable
as String,title: null == title ? _self.title : title // ignore: cast_nullable_to_non_nullable
as String,subtitle: null == subtitle ? _self.subtitle : subtitle // ignore: cast_nullable_to_non_nullable
as String,priority: null == priority ? _self.priority : priority // ignore: cast_nullable_to_non_nullable
as TaskPriority,createdAt: null == createdAt ? _self.createdAt : createdAt // ignore: cast_nullable_to_non_nullable
as DateTime,isAutoGenerated: null == isAutoGenerated ? _self.isAutoGenerated : isAutoGenerated // ignore: cast_nullable_to_non_nullable
as bool,
  ));
}


}

// dart format on
