// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOGmIh_uCSGLe3nvqTRaOFbA0TCIWOKuY',
    appId: '1:720928546774:web:0145ca7e3845d918f0ce77',
    messagingSenderId: '720928546774',
    projectId: 'city-swim',
    authDomain: 'city-swim.firebaseapp.com',
    storageBucket: 'city-swim.firebasestorage.app',
    measurementId: 'G-J1F84B4M4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCksupN7sWAU7vKvijngNnbRnroTjHBnes',
    appId: '1:720928546774:android:4ef30433593af253f0ce77',
    messagingSenderId: '720928546774',
    projectId: 'city-swim',
    storageBucket: 'city-swim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi2mks7HZKswKlEmiENi_6JluEqyIltzk',
    appId: '1:720928546774:ios:bb4e758c45782993f0ce77',
    messagingSenderId: '720928546774',
    projectId: 'city-swim',
    storageBucket: 'city-swim.firebasestorage.app',
    iosBundleId: 'city.swim.school',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi2mks7HZKswKlEmiENi_6JluEqyIltzk',
    appId: '1:720928546774:ios:d47c7ec5d38e88f5f0ce77',
    messagingSenderId: '720928546774',
    projectId: 'city-swim',
    storageBucket: 'city-swim.firebasestorage.app',
    iosBundleId: 'com.example.swimmingSchoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOGmIh_uCSGLe3nvqTRaOFbA0TCIWOKuY',
    appId: '1:720928546774:web:6c7416ae2e5861f6f0ce77',
    messagingSenderId: '720928546774',
    projectId: 'city-swim',
    authDomain: 'city-swim.firebaseapp.com',
    storageBucket: 'city-swim.firebasestorage.app',
    measurementId: 'G-Y69V7DJ3KL',
  );
}
