import 'dart:io';
import 'dart:convert';

void main() {
  final keys = {
    'uk': {
      'coach.tab_schedule': 'Розклад',
      'coach.tab_profile': 'Профіль',
      'coach.logout': 'Вийти',
      
      'admin.quick_actions': 'ШВИДКІ ДІЇ',
      'admin.new_client': 'Новий Клієнт',
      'admin.booking': 'Запис',
      'admin.chat': 'Чат (3 нові)',
      'admin.payment': 'Оплата',
      'admin.tasks_today': 'ЗАВДАННЯ НА СЬОГОДНІ',
      'admin.task_payment': 'Підтвердити оплату',
      'admin.task_payment_desc': 'Клієнт: Марія, Група Юніори',
      'admin.task_call': 'Зателефонувати новеньким',
      'admin.task_call_desc': '3 пропущених дзвінка',
      'admin.task_schedule': 'Оновити розклад',
      'admin.task_schedule_desc': 'Тренер Алекс захворів',
      'admin.hello': 'Вітаємо',
      'admin.search_hint': 'Пошук клієнта, групи, або транзакції...',
      'admin.in_pool': 'Зараз у басейні',
      'admin.clients_count': '24 клієнта',
      'admin.coaches_count': '3 тренери',
      'admin.task_done': 'Завдання виконано!',
      'admin.task_postponed': 'Завдання відкладено',
      
      'owner.business_overview': 'ОГЛЯД БІЗНЕСУ',
      'owner.financial_metrics': 'Фінансові Метрики',
      'owner.reports': 'Звіти',
      'owner.staff': 'Персонал',
      'owner.payouts': 'Виплати',
      'owner.clients': 'Клієнти',
      'owner.occupancy': 'Завантаження',
      'owner.live_status': 'LIVE СТАТУС',
      'owner.new_payment': 'Нова оплата: Абонемент',
      'owner.today_time': 'Сьогодні, 14:30',
      'owner.new_client': 'Новий клієнт: Олена',
      'owner.salary_payout': 'Виплата зарплати',
      'owner.hello': 'Вітаємо',
      'owner.total_revenue': 'ЗАГАЛЬНИЙ ДОХІД (МІСЯЦЬ)',
      'owner.profit_dynamics': 'ДИНАМІКА ПРИБУТКУ',
      'owner.day': 'День',
      'owner.week': 'Тиждень',
      'owner.month': 'Місяць',
      'owner.transaction_details': 'Деталі транзакції',
    },
    'en': {
      'coach.tab_schedule': 'Schedule',
      'coach.tab_profile': 'Profile',
      'coach.logout': 'Logout',
      
      'admin.quick_actions': 'QUICK ACTIONS',
      'admin.new_client': 'New Client',
      'admin.booking': 'Booking',
      'admin.chat': 'Chat (3 new)',
      'admin.payment': 'Payment',
      'admin.tasks_today': 'TODAY\'S TASKS',
      'admin.task_payment': 'Confirm payment',
      'admin.task_payment_desc': 'Client: Maria, Juniors',
      'admin.task_call': 'Call new leads',
      'admin.task_call_desc': '3 missed calls',
      'admin.task_schedule': 'Update schedule',
      'admin.task_schedule_desc': 'Coach Alex is sick',
      'admin.hello': 'Welcome',
      'admin.search_hint': 'Search client, group, or transaction...',
      'admin.in_pool': 'Now in pool',
      'admin.clients_count': '24 clients',
      'admin.coaches_count': '3 coaches',
      'admin.task_done': 'Task completed!',
      'admin.task_postponed': 'Task postponed',
      
      'owner.business_overview': 'BUSINESS OVERVIEW',
      'owner.financial_metrics': 'Financial Metrics',
      'owner.reports': 'Reports',
      'owner.staff': 'Staff',
      'owner.payouts': 'Payouts',
      'owner.clients': 'Clients',
      'owner.occupancy': 'Occupancy',
      'owner.live_status': 'LIVE STATUS',
      'owner.new_payment': 'New payment: Sub',
      'owner.today_time': 'Today, 14:30',
      'owner.new_client': 'New client: Olena',
      'owner.salary_payout': 'Salary payout',
      'owner.hello': 'Welcome',
      'owner.total_revenue': 'TOTAL REVENUE (MONTH)',
      'owner.profit_dynamics': 'PROFIT DYNAMICS',
      'owner.day': 'Day',
      'owner.week': 'Week',
      'owner.month': 'Month',
      'owner.transaction_details': 'Transaction details',
    },
    'de': {
      'coach.tab_schedule': 'Zeitplan',
      'coach.tab_profile': 'Profil',
      'coach.logout': 'Abmelden',
      
      'admin.quick_actions': 'SCHNELLAKTIONEN',
      'admin.new_client': 'Neuer Kunde',
      'admin.booking': 'Buchung',
      'admin.chat': 'Chat (3 neu)',
      'admin.payment': 'Zahlung',
      'admin.tasks_today': 'HEUTIGE AUFGABEN',
      'admin.task_payment': 'Zahlung bestätigen',
      'admin.task_payment_desc': 'Kunde: Maria, Junioren',
      'admin.task_call': 'Leads anrufen',
      'admin.task_call_desc': '3 verpasste Anrufe',
      'admin.task_schedule': 'Zeitplan aktualisieren',
      'admin.task_schedule_desc': 'Trainer Alex ist krank',
      'admin.hello': 'Willkommen',
      'admin.search_hint': 'Kunde, Gruppe oder Transaktion suchen...',
      'admin.in_pool': 'Jetzt im Pool',
      'admin.clients_count': '24 Kunden',
      'admin.coaches_count': '3 Trainer',
      'admin.task_done': 'Aufgabe erledigt!',
      'admin.task_postponed': 'Aufgabe verschoben',
      
      'owner.business_overview': 'GESCHÄFTSÜBERSICHT',
      'owner.financial_metrics': 'Finanzkennzahlen',
      'owner.reports': 'Berichte',
      'owner.staff': 'Personal',
      'owner.payouts': 'Auszahlungen',
      'owner.clients': 'Kunden',
      'owner.occupancy': 'Auslastung',
      'owner.live_status': 'LIVE-STATUS',
      'owner.new_payment': 'Neue Zahlung: Abo',
      'owner.today_time': 'Heute, 14:30',
      'owner.new_client': 'Neuer Kunde: Olena',
      'owner.salary_payout': 'Gehaltsauszahlung',
      'owner.hello': 'Willkommen',
      'owner.total_revenue': 'GESAMTUMSATZ (MONAT)',
      'owner.profit_dynamics': 'GEWINNDYNAMIK',
      'owner.day': 'Tag',
      'owner.week': 'Woche',
      'owner.month': 'Monat',
      'owner.transaction_details': 'Transaktionsdetails',
    },
    'ru': {
      'coach.tab_schedule': 'Расписание',
      'coach.tab_profile': 'Профиль',
      'coach.logout': 'Выйти',
      
      'admin.quick_actions': 'БЫСТРЫЕ ДЕЙСТВИЯ',
      'admin.new_client': 'Новый Клиент',
      'admin.booking': 'Запись',
      'admin.chat': 'Чат (3 новых)',
      'admin.payment': 'Оплата',
      'admin.tasks_today': 'ЗАДАЧИ НА СЕГОДНЯ',
      'admin.task_payment': 'Подтвердить оплату',
      'admin.task_payment_desc': 'Клиент: Мария, Юниоры',
      'admin.task_call': 'Позвонить новым',
      'admin.task_call_desc': '3 пропущенных звонка',
      'admin.task_schedule': 'Обновить расписание',
      'admin.task_schedule_desc': 'Тренер Алекс заболел',
      'admin.hello': 'Добро пожаловать',
      'admin.search_hint': 'Поиск клиента, группы или транзакции...',
      'admin.in_pool': 'Сейчас в бассейне',
      'admin.clients_count': '24 клиента',
      'admin.coaches_count': '3 тренера',
      'admin.task_done': 'Задача выполнена!',
      'admin.task_postponed': 'Задача отложена',
      
      'owner.business_overview': 'ОБЗОР БИЗНЕСА',
      'owner.financial_metrics': 'Финансовые Метрики',
      'owner.reports': 'Отчеты',
      'owner.staff': 'Персонал',
      'owner.payouts': 'Выплаты',
      'owner.clients': 'Клиенты',
      'owner.occupancy': 'Загруженность',
      'owner.live_status': 'LIVE СТАТУС',
      'owner.new_payment': 'Новая оплата: Абонемент',
      'owner.today_time': 'Сегодня, 14:30',
      'owner.new_client': 'Новый клиент: Елена',
      'owner.salary_payout': 'Выплата зарплаты',
      'owner.hello': 'Добро пожаловать',
      'owner.total_revenue': 'ОБЩИЙ ДОХОД (МЕСЯЦ)',
      'owner.profit_dynamics': 'ДИНАМИКА ПРИБЫЛИ',
      'owner.day': 'День',
      'owner.week': 'Неделя',
      'owner.month': 'Месяц',
      'owner.transaction_details': 'Детали транзакции',
    }
  };

  for (final lang in keys.keys) {
    final file = File('assets/translations/$lang.json');
    if (file.existsSync()) {
      final str = utf8.decode(file.readAsBytesSync());
      final map = jsonDecode(str) as Map<String, dynamic>;
      
      map.addAll(keys[lang]!);
      
      file.writeAsBytesSync(utf8.encode(JsonEncoder.withIndent('  ').convert(map)));
      print('Updated $lang.json with additional portal keys');
    }
  }
}
